name: Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run weekly on Mondays at 9am UTC
    - cron: '0 9 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install security tools
      run: |
        pip install bandit safety pip-audit

    - name: Run Bandit (security linter)
      run: |
        bandit -r pm_prompt_toolkit/ ai_models/ -f json -o bandit-report.json
      continue-on-error: true

    - name: Check dependencies for vulnerabilities
      run: |
        safety check --json || true
        pip-audit --desc || true

    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: bandit-report
        path: bandit-report.json

  secret-scanning:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for secret scanning

    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
